# Generated by Django 5.1.7 on 2025-03-31 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personnel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='myapp.studentrecord')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'personnel', 'date')},
            },
        ),
    ]
