# Generated by Django 5.1.6 on 2025-03-15 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFlightGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_flight_groups', to='myapp.announcement')),
                ('flight_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_groups', to='myapp.flightgroup')),
            ],
            options={
                'unique_together': {('event', 'flight_group')},
            },
        ),
    ]
