# Generated by Django 5.1.6 on 2025-03-23 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='flightgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_attendance', to='myapp.personnel'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='myapp.studentrecord'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf', models.IntegerField()),
                ('date', models.DateField()),
                ('cadet_sign', models.CharField(blank=True, max_length=100)),
                ('activity_description', models.TextField()),
                ('merits', models.IntegerField(default=0)),
                ('demerits', models.IntegerField(default=0)),
                ('flight_leader_sign', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_activities', to='myapp.personnel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='myapp.studentrecord')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSpecialCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('band', 'Band Member'), ('office', 'Office Worker'), ('other_gender', 'Other Gender Preference')], max_length=20)),
                ('handler_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_special_cases', to='myapp.personnel')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_case', to='myapp.studentrecord')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_periods', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('num_merits', models.IntegerField(default=0)),
                ('num_demerits', models.IntegerField(default=0)),
                ('subject_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('military_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('proficiency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_grade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to='myapp.personnel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='myapp.studentrecord')),
            ],
            options={
                'unique_together': {('student', 'personnel')},
            },
        ),
    ]
