# Generated by Django 5.1.6 on 2025-03-03 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadfiles_announcement_personnel_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personnel')),
                ('upload_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.uploadfiles')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('personnel', 'upload_file', 'date')},
            },
        ),
    ]
