# Generated by Django 5.1.6 on 2025-03-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_eventflightgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='myapp.personnel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_personnel', to='myapp.studentrecord')),
            ],
            options={
                'ordering': ['personnel__last_name', 'student__name'],
                'unique_together': {('student',)},
            },
        ),
    ]
