# Generated by Django 5.1.6 on 2025-03-03 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAttendanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personnel')),
                ('upload_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.uploadfiles')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'unique_together': {('upload_file', 'assigned_personnel', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personnel')),
                ('uploaded_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.uploadedattendancedata')),
            ],
            options={
                'ordering': ['-uploaded_data__date', '-marked_at'],
                'unique_together': {('uploaded_data', 'personnel')},
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
