# Generated by Django 5.1.6 on 2025-03-03 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_uploadedattendancedata_attendancerecord_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='UploadedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('extra_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_data', to='myapp.personnel')),
                ('upload_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.uploadfiles')),
            ],
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='uploaded_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='myapp.uploadeddata'),
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='marked_by',
        ),
        migrations.DeleteModel(
            name='UploadedAttendanceData',
        ),
    ]
