# Generated by Django 5.1.7 on 2025-04-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_studentrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='user',
        ),
    ]
