# Generated by Django 5.1.6 on 2025-03-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
