# Generated by Django 5.1.7 on 2025-04-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_studentrecord_initial_password_studentrecord_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='initial_password',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='username',
        ),
    ]
