# Generated by Django 5.1.7 on 2025-04-05 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_studentrecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccountChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_changes', to='myapp.studentrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
